# Generated by Django 3.2.6 on 2022-06-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('image2', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('image3', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('price', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category')),
            ],
        ),
    ]
